[package]
name = "penguindevs/boattween"
description = "This module offers 32 easing styles (compared to Roblox's 11) and they all have the 3 easing directions as well, allowing you to find exactly the tween timing you desire. (same thing as nightcycle/boattween, except this package should work straight away instead of erroring without needing to edit the package's index)"
version = "1.0.1"
license = "MIT"
authors = ["boatbomber <zack@boatbomber.com>"]
registry = "https://github.com/upliftgames/wally-index"
realm = "shared"